version: '3.9'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank-system
  api:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@db:5432/bank-system?sslmode=disable
    depends_on:
      - db
    entrypoint: ["/app/wait-for.sh", "db:5432", "--", "/app/startup.sh"]
    command: ["/app/main"]
